INFO:root:No suitable token exists in cache. Let's get a new one from AAD.
INFO:root:1611109950.1284952,b'ahmadchaiban',0,0,0
INFO:root:1611109950.855388,b'ahmadchaiban',5,1,0
INFO:root:1611109951.546171,b'ahmadchaiban',5,1,0
INFO:root:1611109952.305794,b'ahmadchaiban',5,1,0
INFO:root:1611109953.027217,b'ahmadchaiban',0,0,0
INFO:root:1611109953.757354,b'ahmadchaiban',0,0,0
INFO:root:1611109954.446419,b'ahmadchaiban',0,0,0
INFO:root:1611109955.137555,b'ahmadchaiban',0,0,0
INFO:root:1611109955.832963,b'ahmadchaiban',0,0,0
INFO:root:1611109956.523658,b'ahmadchaiban',0,0,0
INFO:root:1611109957.327669,b'ahmadchaiban',0,0,0
INFO:root:1611109958.516096,b'ahmadchaiban',55,11,0
INFO:root:1611109958.517955,b'ahmadchaiban',10,2,0
INFO:root:1611109959.707833,b'ahmadchaiban',5,1,0
INFO:root:1611109959.710933,b'ahmadchaiban',5,1,0
INFO:root:1611109961.280361,b'ahmadchaiban',20,4,0
INFO:root:1611109961.2866912,b'ahmadchaiban',20,4,0
INFO:root:1611109961.616776,b'ahmadchaiban',0,0,0
INFO:root:1611109963.3729339,b'ahmadchaiban',0,0,0
INFO:root:1611109963.376101,b'ahmadchaiban',10,2,0
INFO:root:1611109963.4381068,b'ahmadchaiban',10,2,0
INFO:root:1611109965.4372292,b'ahmadchaiban',0,0,0
INFO:root:1611109965.437401,b'ahmadchaiban',0,0,0
INFO:root:1611109965.729215,b'ahmadchaiban',0,1,0
INFO:root:1611109966.289935,b'ahmadchaiban',0,1,0
INFO:root:1611109968.2423081,b'ahmadchaiban',0,1,0
INFO:root:1611109968.244437,b'ahmadchaiban',0,1,0
INFO:root:1611109968.245951,b'ahmadchaiban',0,0,0
INFO:root:1611109968.247248,b'ahmadchaiban',0,0,0
INFO:root:1611109970.378755,b'ahmadchaiban',15,1,0
INFO:root:1611109970.380686,b'ahmadchaiban',15,1,0
INFO:root:1611109970.3812218,b'ahmadchaiban',15,1,0
INFO:root:1611109970.382032,b'ahmadchaiban',15,1,0
INFO:root:1611109972.746764,b'ahmadchaiban',10,0,0
INFO:root:1611109972.7473521,b'ahmadchaiban',10,0,0
INFO:root:1611109972.749759,b'ahmadchaiban',10,0,0
INFO:root:1611109972.749913,b'ahmadchaiban',10,0,0
INFO:root:1611109975.142617,b'ahmadchaiban',0,0,0
INFO:root:1611109975.1450372,b'ahmadchaiban',0,0,0
INFO:root:1611109975.146126,b'ahmadchaiban',0,0,0
INFO:root:1611109975.149482,b'ahmadchaiban',0,0,0
INFO:root:1611109977.42131,b'ahmadchaiban',0,0,0
INFO:root:1611109977.421427,b'ahmadchaiban',0,0,0
INFO:root:1611109977.4220679,b'ahmadchaiban',50,10,0
INFO:root:1611109977.424146,b'ahmadchaiban',0,0,0
INFO:root:1611109979.7393322,b'ahmadchaiban',0,0,0
INFO:root:1611109979.7394319,b'ahmadchaiban',0,0,0
INFO:root:1611109979.74095,b'ahmadchaiban',0,0,0
INFO:root:1611109979.7417548,b'ahmadchaiban',0,0,0
INFO:root:1611109981.9973419,b'ahmadchaiban',0,1,0
INFO:root:1611109981.997547,b'ahmadchaiban',0,1,0
INFO:root:1611109981.9978838,b'ahmadchaiban',0,1,0
INFO:root:1611109981.9993842,b'ahmadchaiban',0,1,0
INFO:root:1611109983.786443,b'ahmadchaiban',0,0,0
INFO:root:1611109984.40195,b'ahmadchaiban',25,5,0
INFO:root:1611109984.422912,b'ahmadchaiban',25,5,0
INFO:root:1611109984.4236622,b'ahmadchaiban',25,5,0
INFO:root:1611109986.288318,b'ahmadchaiban',0,0,0
INFO:root:1611109986.4392698,b'ahmadchaiban',40,8,0
INFO:root:1611109986.4437041,b'ahmadchaiban',0,0,0
INFO:root:1611109987.6211798,b'ahmadchaiban',0,0,0
INFO:root:1611109988.472001,b'ahmadchaiban',45,9,0
INFO:root:1611109988.580672,b'ahmadchaiban',45,9,0
INFO:root:1611109988.673567,b'ahmadchaiban',45,9,0
INFO:root:1611109989.389406,b'ahmadchaiban',0,0,0
INFO:root:1611109990.8576498,b'ahmadchaiban',20,4,0
INFO:root:1611109990.861375,b'ahmadchaiban',20,4,0
INFO:root:1611109990.861482,b'ahmadchaiban',20,4,0
INFO:root:1611109990.863743,b'ahmadchaiban',0,0,0
INFO:root:1611109992.623001,b'ahmadchaiban',0,0,0
INFO:root:1611109993.243037,b'ahmadchaiban',25,5,0
INFO:root:1611109993.3361778,b'ahmadchaiban',25,5,0
INFO:root:1611109993.3377228,b'ahmadchaiban',25,5,0
INFO:root:1611109994.3211908,b'ahmadchaiban',5,1,0
INFO:root:1611109995.33506,b'ahmadchaiban',0,0,0
INFO:root:1611109995.479916,b'ahmadchaiban',0,0,0
INFO:root:1611109995.7042189,b'ahmadchaiban',15,1,0
INFO:root:1611109996.061708,b'ahmadchaiban',0,0,0
INFO:root:1611109997.672849,b'ahmadchaiban',0,0,0
INFO:root:1611109997.683264,b'ahmadchaiban',10,2,0
INFO:root:1611109997.684368,b'ahmadchaiban',10,2,0
INFO:root:1611109999.023296,b'ahmadchaiban',0,0,0
INFO:root:1611109999.95411,b'ahmadchaiban',0,1,0
INFO:root:1611109999.954787,b'ahmadchaiban',0,1,0
INFO:root:1611109999.9605298,b'ahmadchaiban',0,1,0
INFO:root:1611110001.3259258,b'ahmadchaiban',0,0,0
ERROR:app:Exception on /processImage [POST]
Traceback (most recent call last):
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 84, in enterprise_shield_process_per_frame
    frame = yolo_net.yolo_main(frame, face_net.risk_score, face_net)
  File "/Users/ahmadchaiban/Desktop/Guelph/Fall 2020/6510_Project/server/models/yolo_human_detect.py", line 82, in yolo_main
    frame = self.draw_yolo_result(frame, boxes, confidences, class_ids, class_id)
  File "/Users/ahmadchaiban/Desktop/Guelph/Fall 2020/6510_Project/server/models/yolo_human_detect.py", line 61, in draw_yolo_result
    indices = cv2.dnn.NMSBoxes(boxes, confidences, 0.1, 0.1)
OverflowError: Python int too large to convert to C long
ERROR:app:Exception on /processImage [POST]
Traceback (most recent call last):
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 84, in enterprise_shield_process_per_frame
    frame = yolo_net.yolo_main(frame, face_net.risk_score, face_net)
  File "/Users/ahmadchaiban/Desktop/Guelph/Fall 2020/6510_Project/server/models/yolo_human_detect.py", line 82, in yolo_main
    frame = self.draw_yolo_result(frame, boxes, confidences, class_ids, class_id)
  File "/Users/ahmadchaiban/Desktop/Guelph/Fall 2020/6510_Project/server/models/yolo_human_detect.py", line 61, in draw_yolo_result
    indices = cv2.dnn.NMSBoxes(boxes, confidences, 0.1, 0.1)
OverflowError: Python int too large to convert to C long
ERROR:app:Exception on /processImage [POST]
Traceback (most recent call last):
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 84, in enterprise_shield_process_per_frame
    frame = yolo_net.yolo_main(frame, face_net.risk_score, face_net)
  File "/Users/ahmadchaiban/Desktop/Guelph/Fall 2020/6510_Project/server/models/yolo_human_detect.py", line 82, in yolo_main
    frame = self.draw_yolo_result(frame, boxes, confidences, class_ids, class_id)
  File "/Users/ahmadchaiban/Desktop/Guelph/Fall 2020/6510_Project/server/models/yolo_human_detect.py", line 61, in draw_yolo_result
    indices = cv2.dnn.NMSBoxes(boxes, confidences, 0.1, 0.1)
OverflowError: Python int too large to convert to C long
INFO:root:1611110002.5986009,b'ahmadchaiban',0,0,0
INFO:root:1611110003.3832908,b'ahmadchaiban',0,0,0
INFO:root:1611110004.153568,b'ahmadchaiban',0,0,0
INFO:root:1611110004.9378188,b'ahmadchaiban',0,0,0
INFO:root:1611110005.696029,b'ahmadchaiban',0,0,0
INFO:root:1611110006.437302,b'ahmadchaiban',0,0,0
INFO:root:1611110007.209121,b'ahmadchaiban',0,0,0
INFO:root:1611110007.991041,b'ahmadchaiban',0,0,0
INFO:root:1611110008.711663,b'ahmadchaiban',5,1,0
INFO:root:1611110009.456673,b'ahmadchaiban',5,1,0
INFO:root:1611110010.201633,b'ahmadchaiban',0,0,0
INFO:root:1611110010.921768,b'ahmadchaiban',5,1,0
INFO:root:1611110011.63277,b'ahmadchaiban',5,1,0
INFO:root:1611110012.462738,b'ahmadchaiban',0,0,0
INFO:root:1611110013.210598,b'ahmadchaiban',0,0,0
INFO:root:1611110013.987937,b'ahmadchaiban',0,0,0
INFO:root:1611110014.7818189,b'ahmadchaiban',0,0,0
INFO:root:1611110015.574229,b'ahmadchaiban',0,0,0
INFO:root:1611110016.377772,b'ahmadchaiban',0,0,0
INFO:root:1611110017.134926,b'ahmadchaiban',0,0,0
INFO:root:1611110017.949597,b'ahmadchaiban',0,0,0
INFO:root:1611110019.042542,b'ahmadchaiban',0,0,0
INFO:root:1611110019.876297,b'ahmadchaiban',0,0,0
INFO:root:1611110020.677232,b'ahmadchaiban',0,0,0
INFO:root:1611110021.459075,b'ahmadchaiban',0,0,0
INFO:root:1611110022.269155,b'ahmadchaiban',0,0,0
INFO:root:1611110023.003916,b'ahmadchaiban',0,0,0
ERROR:waitress:Socket error
Traceback (most recent call last):
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/waitress/channel.py", line 118, in handle_write
    flush()
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/waitress/channel.py", line 227, in _flush_some
    num_sent = self.send(chunk)
  File "/Users/ahmadchaiban/opt/anaconda3/lib/python3.7/site-packages/waitress/wasyncore.py", line 433, in send
    result = self.socket.send(data)
OSError: [Errno 41] Protocol wrong type for socket
